#Knock Knock Jokes
print("Joke 1")
joke1 = input("Knock Knock")
joke1butsentence2 = input("Dwayne")
print("Dwayne the bathtub I'm drowning")
print("Joke 2")
joke2 = input("Knock Knock")
joke2butsentence2 = input("Toad")
print("Toad on ya")
print("Joke 3")
joke3 = input("Knock Knock")
joke3butsentence2 = input("Ya")
print("You said Yahoo!")