import string
import random
def savePassword(text, fileName):
    saveText = open(f"{fileName}.txt", "a")
    saveText.write(f"{text}\n")
    saveText.close()
uppercase = string.ascii_uppercase
lowercase = string.ascii_lowercase
digits = string.digits
password = []
password.extend(list(uppercase))
password.extend(list(lowercase))
password.extend(list(digits))
passwordLength = int(input("Enter The Password Length : "))
random.shuffle(password)
finalPassword = "".join(password[0:passwordLength])
print(finalPassword)
passwordFile = "password.txt"
saveQ = input(f"Do You Want To Save Your Password In {passwordFile} (y/n) : ")
if saveQ=='y' or saveQ=='yes':
    savePassword(f"The Password Which Is Generated By Python Is : {finalPassword}", passwordFile)
    print(f"Your Password Is Saved In {passwordFile}")
else:
    pass