import turtle
import time
bbbbbbbbbbbbbbaaaaaaaaaaaaaaaalllllllllllooooooooooooooooon = turtle.Turtle()
bbbbbbbbbbbbbbaaaaaaaaaaaaaaaalllllllllllooooooooooooooooon.right(-90)
time.sleep(0.1)
bbbbbbbbbbbbbbaaaaaaaaaaaaaaaalllllllllllooooooooooooooooon.forward(90)
time.sleep(0.1)
bbbbbbbbbbbbbbaaaaaaaaaaaaaaaalllllllllllooooooooooooooooon.right(45)
time.sleep(0.1)
bbbbbbbbbbbbbbaaaaaaaaaaaaaaaalllllllllllooooooooooooooooon.forward(50)
time.sleep(0.1)
bbbbbbbbbbbbbbaaaaaaaaaaaaaaaalllllllllllooooooooooooooooon.left(45)
time.sleep(0.1)
bbbbbbbbbbbbbbaaaaaaaaaaaaaaaalllllllllllooooooooooooooooon.forward(50)
time.sleep(0.1)
bbbbbbbbbbbbbbaaaaaaaaaaaaaaaalllllllllllooooooooooooooooon.left(45)
time.sleep(0.1)
bbbbbbbbbbbbbbaaaaaaaaaaaaaaaalllllllllllooooooooooooooooon.forward(50)
time.sleep(0.1)
bbbbbbbbbbbbbbaaaaaaaaaaaaaaaalllllllllllooooooooooooooooon.left(90)
time.sleep(0.1)
bbbbbbbbbbbbbbaaaaaaaaaaaaaaaalllllllllllooooooooooooooooon.forward(50)
time.sleep(0.1)
bbbbbbbbbbbbbbaaaaaaaaaaaaaaaalllllllllllooooooooooooooooon.left(45)
time.sleep(0.1)
bbbbbbbbbbbbbbaaaaaaaaaaaaaaaalllllllllllooooooooooooooooon.forward(50)
time.sleep(0.1)
bbbbbbbbbbbbbbaaaaaaaaaaaaaaaalllllllllllooooooooooooooooon.left(45)
time.sleep(0.1)
bbbbbbbbbbbbbbaaaaaaaaaaaaaaaalllllllllllooooooooooooooooon.forward(50)
time.sleep(0.1)
