import pyttsx3 as reader
import time
Rivaan = reader.init()
Rivaan.say("Hi, My name is Reevaan")
print("Hi, My name is Rivaan")
time.sleep(1)
Rivaan.say("My brother is 9 years old")
print("My brother is 9 years old")
time.sleep(1)
Rivaan.say("And I like Minecraft")
print("And I like Minecraft")
time.sleep(1)
Rivaan.say("My second favorite game is Roblox")
print("My second favorite game is Roblox")
time.sleep(1)
Rivaan.say("And I like to do Scratch")
print("And I like to do Scratch")
time.sleep(1)
Rivaan.say("Also I'm 5 years old")
print("Also I'm 5 years old")
time.sleep(1)
Rivaan.say("I love sonic also and I have a sonic toy")
print("I love sonic also and I have a sonic toy")
time.sleep(1)
Rivaan.say("That's my story bye")
print("That's my story bye")
Rivaan.runAndWait()